export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SELF = 'FETCH_POSTS_SELF';
export const NEW_POST = 'NEW_POSTS';
export const FETCH_COMMENTS='FETCH_COMMENTS';
export const NEW_COMMENT = 'NEW_COMMENT';

export const LOGIN_SEND_DATA= 'LOGIN_SEND_DATA';
export const LOGIN_SEND_SESSION= 'LOGIN_SEND_SESSION';

export const LOGIN_RESET_DATA= 'LOGIN_RESET_DATA';


