export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POSTS';
export const FETCH_COMMENTS='FETCH_COMMENTS';
export const NEW_COMMENT = 'NEW_COMMENT';

export const  SESSION_SET= 'SESSION_SET';
export const SESSION_INVAID= 'SESSION_INVAID';

export const LOGIN_SEND_DATA= 'LOGIN_SEND_DATA';
export const LOGIN_RECEIVE_DATA_SUCCESS= 'LOGIN_RECEIVE_DATA_SUCCESS';
export const LOGIN_RECEIVE_DATA_FAILURE= 'LOGIN_RECEIVE_DATA_FAILURE';
